### ISSUE TITLE
Items are not being correctly updated when draging it thought out the table

### ISSUE THREAD

**Issue by milewski** [outl1ne/nova-sortable#139]
Hi, I'm not sure at what version this stopped working, however for quite a while now the sorting "works" behind the scene but the UI does not update correctly when dragging things around.

You can see on the video below after dragging the items reset back to where they were before the drag but if I refresh the page you can see they were correctly sorted (on the db)

https://user-images.githubusercontent.com/2874967/188369654-062ea5e6-e6a4-49cc-8203-c1f3d424a83f.mov

**Comment by miks** [comment]
Same here, but I think it worked some time ago. Maybe some Nova update broke it?

**Comment by miks** [comment]
3.1.0 is fine, the issue started from 3.2.0

**Comment by Tarpsvo** [comment]
That's weird - I can't seem to be able to reproduce this issue. Can you confirm this wasn't related to JS being cached?

**Comment by miks** [comment]
I cleaned cache multiple times. I can repeat with latest Nova and sortable 3.2.1

**Comment by Tarpsvo** [comment]
That's really weird. I wonder why it's not happening for me - am I doing something wrong? Also using the latest Nova (4.17.1).

https://user-images.githubusercontent.com/2018660/198570461-60e1f8d9-b95d-44c1-848c-583d75f60fb0.mp4

**Comment by miks** [comment]
Which browser you used? I tested with Safari.

**Comment by milewski** [comment]
Still not working for me and I tested in chrome... maybe some package we have in common is interfering with it? this is my composer.json

```json
    "require": {
        "php": "^8.1",
        "ext-fileinfo": "*",
        "alexwenzel/nova-dependency-container": "^1.6",
        "brick/phonenumber": "^0.4.0",
        "digital-creative/custom-theme": "*",
        "digital-creative/fractal-documentation": "dev-refactor",
        "dragon-code/laravel-migration-actions": "^2.9",
        "eminiarts/nova-tabs": "^2.2.2",
        "fakerphp/faker": "^1.20",
        "firebase/php-jwt": "^6.3",
        "guzzlehttp/guzzle": "^7.5",
        "laravel-lang/publisher": "^14.3.3",
        "laravel/framework": "^9.35.1",
        "laravel/horizon": "^5.10.2",
        "laravel/nova": "^4.16.1",
        "laravel/sanctum": "^2.15.1",
        "laravel/scout": "^9.4.12",
        "laravel/telescope": "^4.9.4",
        "laravel/tinker": "^2.7.2",
        "league/flysystem-aws-s3-v3": "^3.5",
        "meilisearch/meilisearch-php": "^0.24.2",
        "mockery/mockery": "^1.5.1",
        "norman-huth/nova-values-field": "^1.0.1",
        "oneduo/nova-file-manager": "^0.7",
        "outl1ne/nova-sortable": "^3.2.1",
        "outl1ne/nova-translatable": "^2.1.1",
        "overtrue/laravel-query-logger": "^3.0",
        "pktharindu/nova-permissions": "^3.0",
        "spatie/image": "^2.2.4",
        "spatie/laravel-data": "^2.0.12",
        "spatie/laravel-ignition": "^1.5.1",
        "spatie/laravel-model-states": "^2.4.2",
        "stripe/stripe-php": "^9.6",
        "whitecube/nova-flexible-content": "^1.0.5",
        "worksome/request-factories": "^2.5"
    },
    "require-dev": {
        "barryvdh/laravel-ide-helper": "^2.12.3",
        "brianium/paratest": "^6.6.4",
        "digital-creative/ecs": "dev-development",
        "laravel-lang/attributes": "^2.0.6",
        "laravel-lang/lang": "^11.0.19",
        "nunomaduro/collision": "^6.3.1",
        "pestphp/pest": "^1.22.1",
        "pestphp/pest-plugin-laravel": "^1.3",
        "pestphp/pest-plugin-parallel": "^1.2",
        "phpunit/phpunit": "^9.5.25",
        "spatie/pest-plugin-test-time": "^1.1.1"
    },
```

**Comment by Tarpsvo** [comment]
I released version 3.3.0 which updates the Vue version and rearranges the :key parameter on the row (just a theoretical fix). Can you try out the latest version and let me know if anything's changed? Thanks!

**Comment by milewski** [comment]
I upgraded, made sure the cache was cleared and tested on firefox/edge/chrome, and I'm still unable to sort...

**Comment by IgorMeta** [comment]
I also have a buggy sorting of the translated field.
https://github.com/outl1ne/nova-sortable/issues/149
If you disable outl1ne/nova-translatable, then everything works as it should

**Comment by KasparRosin** [comment]
Try out the latest 3.4.0 branch.
I updated the :key value, so now Vue should update the view correctly.
